services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: eTutoring-container
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__DefaultConnection=Host=db;Database=eTutoringDB;Username=eTutoringSql;Password=eTutoring123
    volumes:
      - .:/src
      - /src/obj/
      - /src/bin/
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: my-postgres
    restart: always
    environment:
      - POSTGRES_USER=eTutoringSql
      - POSTGRES_PASSWORD=eTutoring123
      - POSTGRES_DB=eTutoringDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
